// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54b6d885-2212-4187-87b8-a4fcdd4de3bd"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 6, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8359),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("e250f169-8e54-4c19-89a8-f78304f06bf1"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 7, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8400),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("e61f6340-e5f0-4bc9-8bb9-27f8a01887d0"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 9, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8405),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("42b8e77e-1cd4-419a-8e7b-31e4627579b1"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 10, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8409),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("4747e354-70e5-4ecf-b1e5-8e68ae63833d"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 11, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8426),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("962875e6-7a89-4fa8-8777-a669577e1a6b"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 12, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8430),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("1f767678-4036-4e15-8e8d-5c9dba2c4744"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 1, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8434),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("9e927783-d21e-4124-800d-51c7a52bab2b"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 2, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8438),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("86925162-2ff7-42b3-bd9e-a8846ce36d43"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 3, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8442),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("a55ff768-6453-4474-8e4c-969e5cb19cb9"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2023, 4, 5, 21, 25, 42, 278, DateTimeKind.Local).AddTicks(8446),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
